export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const FRIEND_REQUEST_SUCCESS = 'FRIEND_REQUEST_SUCCESS';
export const FRIEND_REQUEST_ERROR = 'FRIEND_REQUEST_ERROR';

export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const GET_FRIENDS_ERROR = 'GET_FRIENDS_ERROR';

export const GET_CHAT_MESSAGE = 'GET_CHAT_MESSAGE';
export const GET_CHAT_MESSAGE_ERROR = 'GET_CHAT_MESSAGE_ERROR';
